# This file controls the settings for your Quarto template from www.marvinschmitt.com
# website settings
website:
  title: "Santosh D. Bhosale"
  description: "Proteomics scientist & AI/ML drug discovery lead. PhD · 15+ years · 20+ publications · Partex.ai"
  image: img/sdb.png
  google-analytics: "G-GVC1LWDBTL"
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Academic"
        menu:
          - text: "CV (Web)"
            href: cv/index.qmd
          - text: "Resume (PDF)"
            href: cv/Resume.pdf
          - text: "---"
          - text: "PhD Thesis"
            href: cv/Thesis.pdf
      - text: "Blog"
        href: blog/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/santoshdbhosale/
      - icon: github
        href: https://github.com/santoshdbhosale
      - text: "{{< iconify academicons google-scholar size=1.5em >}}"
        href: https://scholar.google.com/citations?user=sIxWbx0AAAAJ&hl=en
      - icon: envelope
        aria-label: email
        href: "mailto:santoshdbhosale@gmail.com"  
  
# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  
project:
  type: website
  output-dir: docs
  resources:
    - "cv/*.pdf"
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true
execute:
  freeze: true
format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true