---
title: "Proteomics data analysis and _visualization_ (no programming skills..its okay..but)"
date: 2023-10-10
categories:
  - data analysis
---

Mass spectrometry based proteomics is a versatile technique to identify and characterize the proteins (including their interaction, alternative splicing, post-transnational modifications and more). Introduction and details about the technology are beyond the scope of this blog post, however, readers are recommended to follow the [comprehensive overview of modern proteomics](https://jessegmeyerlab.github.io/proteomics-tutorial/).

Typical shotgun proteomics experiment on representative number of samples results in generation of several gigabytes of mass spectrometry data files. The analysis of such data undergoes following steps.

-   Quality control checks.
-   Database search and quantitative analysis.
-   Statistical analysis
-   Functional annotation analysis

In this blog post, I will highlight the exploratory analysis tools used to process the mass spectrometry data. Such analysis gives an overview of high-dimensional biological data, guidance for further analysis and hypothesis testing. The tools include free and proprietary softwares.

1.  **Quality control checks:** Depending on the mode of LC-MS/MS data acquisition (i.e. either DDA or DIA), there exist plethora of tools to measure QC metrics. However, for the DIA analysis, limited pipelines are available.

    Often times to use the functionality of some tools, users needs to convert the proprietary MS files into generic file format such as mzmL

    *DDA analysis*

    -   [RawMeat](https://proteomicsresource.washington.edu/protocols06/): developed by Vast Scientific gives a quick overview of TIC (total ion chromatogram), charge state distribution, fill time, spray stability and target fill times. The tool is limited to use with Thermo instrument and it is no longer supported.
    -   [RawBeans](https://bitbucket.org/incpm/prot-qc/downloads/): generates an interactive html report for
    -   [QuiC ™](https://biognosys.com/software/quic/): Properitary software from Biognosys, supports most of data acquisition mode (SRM, PRM, DIA or DDA) but it requires addition of iRT peptides to the samples.
