---
about:
  template: jolla
  id: about-block
---

::: {#about-block}
:::

Currently, leading an effort to develop biomarker module for omics research. The work involves collaboration with data engineers and data scientists. I contribute to the other modules task related to data extraction from public databases using Llama and Gemini models. Furthermore, putting an effort to accelerate data curation process through scripting.

As an associate scientific manager at Innoplexus Consulting Pvt. Ltd., Pune, India, I worked on data curation part for the outputs generated via different modules built to accelerate the drug discovery and development process using AI and ML approaches. Specifically, I collaborated with product managers, data engineers and data scientist in an agile environment. Besides, data curation, I was also responsible for providing insights on enhancing the performance of LLM models by optimizing the prompts and evaluating its accuracy. 

During my employment as an associate biomedical scientist at Precision biomarker laboratories, Cedars-Sinai Medical Center, Los Angeles, CA, USA, I carried out research and development operations related to clinical proteomics and biomarkers discovery. I was involved in collaborative projects to improve the existing workflow, developing new PTMomics platforms and computational analysis. The work involved working with and supervising laboratory technicians, study execution, report compilation and presentation (end to end delivery).

As a postdoctoral fellow, I worked in Prof. Martin R. Larsen's lab at the University of Southern Denmark on developing a pipeline for identifying post-translationally modified biomarkers in clinical samples.

I pursued my PhD from University of Turku under the joint advisorship of Prof. Riitta Lahesmaa and Dr. Robert Moulder. During the course of studies, I worked on identifying and validating the serum protein biomarkers for type 1 diabetes and carotid atherosclerosis.

Before enrollment into the PhD study, I gained my first level of research experience with my master thesis in the area of proteomics and mass spectrometry at National Chemical Laboratory (NCL) under the joint supervision of Drs. Mahesh J. Kulkarni and B.Santhakumari, after which I continued as a teacher in college of pharmacy and then as a research assistant again at NCL.

